version: '3'

services:
    php: 
        build: ./php
        container_name: php 
        ports: 
            - "80:80"
            - "443:443"
        depends_on: 
            - postgres 
            - redis 
        volumes: 
            - ./www:/var/www  
            - ./php/php.ini:/usr/local/etc/php/conf.d/z-custom.ini
            - ./php/openssl.cnf:/etc/ssl/openssl.cnf
            - ./apache2/sites-available/:/etc/apache2/sites-available/
            - ./apache2/ssl/:/etc/apache2/ssl/
            - ./apache2/logs/:/var/log/apache2/
            - ./apache2/apache2.conf:/etc/apache2/apache2.conf
            - /var/storage/video:/var/www/storage/app/video
    postgres: 
        container_name: postgres 
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: root
        volumes: 
            - ./postgres/data/:/var/lib/postgresql/data
            - ./postgres/dumps:/dumps
    redis:
        container_name: redis 
        image: redis
        restart: always 
        ports: 
            - 6379:6379 
    echo:
        container_name: echo 
        image: lagun4ik/laravel-echo-server 
        #env_file: ./www/.env
        ports:
          - 6001:6001 
        depends_on: 
            - php 
            - redis
        links:
          - php 
          - redis
        volumes:
          - ./echo/:/app/
          - ./apache2/ssl:/etc/apache2/ssl
    openvidu:
        container_name: openvidu
        image: openvidu/openvidu-server-kms:2.11.0
        environment: 
            - openvidu.secret=MY_SECRET 
            - openvidu.publicurl=https://telemed.mznn.ru:4443
            - openvidu.recording=true
            - openvidu.recording.path=/var/storage/video/
            - openvidu.recording.public-access=true
            - KMS_TURN_URL=openvidu:openvidu@192.168.1.183:3478
            - server.ssl.key-store=/app/p12keystore.p12
            - server.ssl.key-store-password=vir77vit
            - server.ssl.key-alias=telemed
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - ./openvidu/:/app/
            - /var/storage/video/:/var/storage/video/
        ports: 
            - 4443:4443
        depends_on: 
            - php
    coturn:
        container_name: coturn
        image: instrumentisto/coturn 
        volumes: 
            - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf 
        network_mode: host